
import React from 'react';

const TermsPage = () => (
    <>
        <section className="max-w-3xl mx-auto py-16 px-4 md:px-0">
            <h1 className="text-3xl md:text-4xl font-bold mb-6 text-center">Terms and Conditions</h1>
            <h2 className="text-xl font-semibold mb-4">GoPrac Agreement</h2>
            <p className="mb-4">The following is an agreement between GoPrac and any person or any legal entity, and in the case of persons under the age of majority, their parent or legal guardian, (“you”, “your” and the “account holder”) who wishes to use the www.GoPrac.com. The following terms and conditions, along with all other terms and legal notices located on www.GoPrac.com (collectively, “Terms”), govern your use of www.GoPrac.com (the “Website”). If you do not understand and agree to be bound by all Terms, do not use this Website. Your use of this Website at anytime constitutes a binding agreement by you to abide by these Terms.</p>

            <h3 className="text-lg font-semibold mt-8 mb-2">1. ACCEPTANCE OF TERMS</h3>
            <p className="mb-4">Welcome to the www.GoPrac.com. Everyone who uses the Service – even on a trial basis – is subject to this Agreement. This Agreement is between you and GoPrac Pvt Ltd. You may not change, supplement or amend this Agreement in any manner. You must be at least 18 years old to use the Service. If you are under the age of 18, you can use this Service only in conjunction with, and under the supervision of your parents or guardians. It is your sole responsibility to determine whether your use of the Service is lawful, and you must comply with all applicable laws in using the Service. GoPrac may unilaterally amend or supplement this Agreement from time to time on notice as permitted in the manner described in this Agreement, and your continued use of the Service shall constitute your acceptance of such amendments. If required by law, GoPrac will notify you at the email address you provide to us on registration and give you prior notice of such amendments and the opportunity to terminate this Agreement if you do not agree with such amendments.</p>

            <h3 className="text-lg font-semibold mt-8 mb-2">2. DESCRIPTION OF SERVICE</h3>
            <p className="mb-4">The Service consists of the provision by GoPrac to you of access to the www.GoPrac.com Educational Community Site, which provides tools to you that will enable you to view online content (in the form of text, images, video, flash), take online tests, learn from educational materials posted, discuss with faculty and other users, send your message to colleges and other allied services. Unless explicitly stated otherwise, any new features that augment or enhance the current Service shall be subject to the terms and conditions of this Agreement. The Service may not be used for any purpose not expressly permitted by this Agreement. You may not reproduce, copy, duplicate, sell or resell any part of the Service. As stipulated elsewhere in this Agreement, GoPrac does not exert any control over any merchants, retailers, commercial ventures or other third parties, and as such is not liable or responsible for any actions taken or omitted to be taken by any such third party.</p>

            <h3 className="text-lg font-semibold mt-8 mb-2">3. REGISTRATION</h3>
            <ul className="list-disc pl-6 mb-4">
                <li>Provide accurate, current and complete information about you as may be prompted by any registration forms on the Site (“Registration Data”)</li>
                <li>Maintain the security of your password and identification</li>
                <li>Receive all kinds of transactional and promotional communications through SMS/Email/Phone or any other medium from GoPrac with respect to your enrollment or any product or service or event.</li>
                <li>Maintain and promptly update the Registration Data, and any other information you provide to GoPrac , to keep it accurate, current and complete</li>
                <li>Be responsible for all use of your account and for any actions that take place using your account.</li>
                <li>Since you are a bonafide student of GoPrac , GoPrac reserves the right to use your details including photographs for promotional/marketing activities. GoPrac also reserves the right to take credit for your success in GATE/PSU/Other entrance exams that you will participate in future. You will not have any objection to GoPrac publishing your photographs in newspaper & other promotional materials claiming credit for the results.</li>
                <li>GoPrac has the sole discretion to change the classroom venue or schedule of the classes.</li>
                <li>If you provide any information that is untrue, inaccurate, not current or incomplete, or GoPrac has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, GoPrac has the right to suspend or terminate your account and refuse any and all current or future use of the Service. You are responsible for all activity occurring on your account and shall abide by all applicable local, provincial, federal and foreign laws, treaties and regulations in connection with your use of the Service, including those related to data privacy. You agree to immediately notify GoPrac of any unauthorized uses of the account or any other breaches of security. GoPrac cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.</li>
                <li>All user names and passwords remain the property of GoPrac and may be canceled, changed or suspended at any time by GoPrac without notice. GoPrac is not under any obligation to verify the actual identity or authority of the user of any user name or password.</li>
            </ul>

            <h3 className="text-lg font-semibold mt-8 mb-2">4. USE OF FORUMS</h3>
            <ul className="list-disc pl-6 mb-4">
                <li>Provide your correct information while sending some message at various forums on www.GoPrac.com</li>
                <li>You agree to use proper, parliamentary language in the forum.</li>
                <li>You agree to not to use language which is abusive or which can hurt feelings of any gender, region, religion etc.</li>
                <li>You agree to report to www.GoPrac.com as soon as you find any such uses.</li>
                <li>You agree to use this forum in most legitimate way.</li>
                <li>You agree and understand that forum is for discussion of educational material and you agree to provide information as per best of your understanding and knowledge.</li>
                <li>You agree to receive all kinds of transactional and promotional communications through SMS/Email/Phone or any other medium from GoPrac with respect to your enrollment or any product or service or event.</li>
            </ul>

            <h3 className="text-lg font-semibold mt-8 mb-2">5. OWNERSHIP OF SITE CONTENT AND LIMITED LICENSE</h3>
            <p className="mb-4">All content on the Site and available through the Service, including but not limited to designs, text, graphics, pictures, video, information, applications, software, music, sound and other files, and their selection and arrangement (the “Site Content”) in addition to the source code, object code, software, content, copyrights, trademarks, patents and other intellectual property related thereto or included therein, is the property of GoPrac , its users or its licensors, with all rights reserved. No Site Content may be modified, copied, distributed, framed, reproduced, republished, downloaded, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, without GoPrac ’s prior written permission, except that (i) the foregoing does not apply to your own User Content that you legally post on the Site, and (ii) any Site Content provided by Third Parties for sale or license through the Site (“Third Party Content”) is subject to the terms and conditions established by those Third Parties from time to time. All suggestions, recommendations, bug- fixes, error-fixes or other communications from You to GoPrac regarding the Application or the Website shall, upon submission to GoPrac , be owned solely and exclusively by GoPrac</p>
            <p className="mb-4">Provided that you are eligible for use of the Site, you are granted, solely for your personal, non-commercial use, non-exclusive, revocable, non-transferable, a limited license to access and use, and to download or print a copy of, any portion of the Site Content, other than Third Party Content, to which you have properly gained access, provided that you keep all copyright or other proprietary notices intact. Such license is subject to these Terms of Use and does not include use of any data mining, robots or similar data gathering or extraction methods. GoPrac , from time to time, update or modify the Site Content, release new versions of or create new modules related thereto, each of which may, at GoPrac discretion, be included within the license described above.</p>
            <p className="mb-4">Any use of the Site or the Site Content other than as specifically authorized herein, without the prior written permission of GoPrac or the applicable Third Party, as the case may be, is strictly prohibited and will terminate the license granted herein. Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws. Unless explicitly stated herein, nothing in these Terms of Use shall be construed as conferring any license to intellectual property rights, whether by estoppels, implication or otherwise. This license is revocable at any time without notice and with or without cause.</p>

            <h3 className="text-lg font-semibold mt-8 mb-2">6. REFUND POLICY</h3>
            <p className="mb-4">GoPrac Private Limited reserves the right, to suspend or terminate the Services at any time in its sole discretion in case any difficulty is encountered in its realisation of the full value of the Fees payable. The violation of any of the terms and conditions by the Subscriber shall be adequate grounds for cancellation of the Service, and no liability shall befall GoPrac Private Limited to refund the fees already paid, either in full or in part. Once the payment has been realized no refund / cancellation will be made on any ground, including but not limited to non-usage of the Service. No scholarships applicable in case of Online payment & Cash On delivery, unless it is a special discount.</p>
            <p className="mb-4">The information from or through the Service is provided on “AS IS” basis. GoPrac Private Limited as also their parent organisations, affiliates , associates and permitted assigns shall not be liable, at any time for damages arising from sudden change/addition in the syllabus, testing pattern, marking pattern, analysis reports, guidance notes, explanations, announcement of exam dates or any of its contents, or from any action taken (or refrained from being taken) as a result of using the Service or any such contents or for any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission or through downloadable material and or software(s) and tools, computer virus, communications line failure, theft or destruction or unauthorized access to, alteration of, or use of information contained on the Service. No representations, warranties or guarantees whatsoever are made as to the accuracy, adequacy, reliability, completeness, suitability or applicability of the information to a particular situation. The Subscriber agrees that GoPrac Private Limited has no responsibility or liability arising from factors including but not limiting to the deletion, corruption, loss or failure to store any messages or content / data maintained or transmitted by the Service, and that no compensation is or shall be payable whatsoever with respect to the aforesaid by GoPrac Pvt Ltd. GoPrac Private Limited MAKES NO WARRANTY THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.</p>

            <h3 className="text-lg font-semibold mt-8 mb-2">7. USE OF WEBSITE</h3>
            <ul className="list-disc pl-6 mb-4">
                <li>Violate any applicable local, provincial, state, national or international law, statute, ordinance, rule or regulation</li>
                <li>Interfere with or disrupt computer networks connected to the Website</li>
                <li>Impersonate any other person or entity, or make any misrepresentation as to your employment by or affiliation with any other person or entity</li>
                <li>Forge headers or in any manner manipulate identifiers in order to disguise the origin of any user information</li>
                <li>Upload, post, transmit, publish, or distribute any material or information for which you do not have all necessary rights and licenses</li>
                <li>Upload, post, transmit, publish or distribute any material which infringes, violates, breaches or otherwise contravenes the rights of any third party, including any copyright, trademark, patent, rights of privacy or publicity or any other proprietary right</li>
                <li>Interfere with or disrupt the use of the Website by any other user, nor “stalk”, threaten, or in any manner harass another user</li>
                <li>Upload, post, transmit, publish, or distribute any material or information which contains a computer virus, or other code, files or programs intending in any manner to disrupt or interfere with the functioning of the Website, or that of other computer systems</li>
                <li>Use the Website in such a manner as to gain unauthorized entry or access to the computer systems of others; upload, post, transmit, publish or distribute any material or information which constitutes or encourages conduct that would constitute a criminal offense, give rise to other liability, or otherwise violate applicable law; upload, post, transmit, publish, or distribute any material or information that is unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous, vulgar, obscene, or racially, ethnically, or otherwise objectionable</li>
                <li>Reproduce, copy, modify, sell, store, distribute or otherwise exploit for any commercial purposes the Website, or any component thereof (including, but not limited to any materials or information accessible through the Website); use any device, software or routine to interfere or attempt to interfere with the proper working of the Website; or take any action that imposes an unreasonable or disproportionately large load on the Website infrastructure.</li>
            </ul>

            <h3 className="text-lg font-semibold mt-8 mb-2">8. Disclaimer</h3>
            <p className="mb-4">The information contained in this site is authentic to the best of our knowledge. However, GoPrac shall not be responsible for unintended errors that may have crept into this site. GoPrac doesn’t provide any warranty that the services provided by it will meet your expectations and requirements. The information and sectional tips provided for various exams should be taken in its spirit of being a suggestive opinion of GoPrac only. Details submitted through website forms either for course registration or event participation can be used as a property of GoPrac and the same can be used for any form of marketing activity.</p>
            <p className="mb-4">Users of GoPrac also provide information/data in the form of discussions, tests etc. GoPrac is not responsible for such data. Any error/abuse on same can be reported by “report abuse” section. GoPrac will remove any objectionable data (if found) at the shortest possible duration. This information is also written without any malice towards anyone or any institution and therefore any offense caused to anyone or any institution concerned or not concerned, is regretted</p>

            <h3 className="text-lg font-semibold mt-8 mb-2">JURISDICTION OF THE COURT</h3>
            <p className="mb-4">All disputes arising under or out of this service or in anyway connected with this service shall be subject to the jurisdiction of the courts of Bangalore.</p>
        </section>
    </>
);

export default TermsPage; 